name: Update Arch Repos
on:
  push:
    branches:
      - main

jobs:
  UpdateRepos:
    needs: ObtainSource
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: "pwd; ls; cd arch-repos && ./scripts/update-repos.sh"
        container:
          image: archlinux:latest
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: .
