name: Update Arch Repos
on:
  push:
    branches:
      - main

jobs:
  UpdateRepos:
    runs-on: archlinux/archlinux:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Update Repos
        run: cd ${{ github.workspace }}/arch-repos/ && ./scripts/update-repos.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: .
