name: Update Arch Repos
on:
  push:
    branches:
      - main

jobs:
  UpdateRepos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: "pacman -Sy --noconfirm git; cd arch-repos && ./scripts/update-repos.sh && git add . && git commit -m 'Deploying to gh-pages' && git push origin gh-pages"
    container:
      image: archlinux:latest
