name: Update Arch Repos
on:
  push:
    branches:
      - main

jobs:
  UpdateRepos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: "pacman -Sy --noconfirm git > /dev/null && cd arch-repos && ./scripts/update-repos.sh && ./scripts/upload-to-gh-pages.sh"
    container:
      image: archlinux:latest
