name: Update Arch Repos
on:
  push:
    branches:
      - main

jobs:
  UpdateRepos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: "pacman -Sy --noconfirm git; cd arch-repos && ./scripts/update-repos.sh"
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: .
    container:
      image: archlinux:latest
