name: Update Arch Repos
on:
  push:
    branches:
      - main

jobs:
  ObtainSource:
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

  UpdateRepos:
    needs: ObtainSource
    steps:
      - run: "./scripts/update-repos.sh"
    container:
      image: archlinux:latest
      volumes:
        - "${{ github.workspace }}:/workspace"
      options: 
        - --entrypoint /usr/bin/bash
        - --workdir /workspace/arch-repos
        - --cpus 1

  UploadToGHPages:
    needs: UpdateRepos
    steps:
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: .
