name: Update Arch Repos
on:
  push:
    branches:
      - main

jobs:
  ObtainSource:
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

  UpdateRepos:
    steps:
      - container:
          image: archlinux:latest
          volumes:
            - "${{ github.workspace }}:/workspace"
          command:
            - "--entrypoint /usr/bin/bash"
            - "--workdir /workspace/arch-repos"
            - "-c ./scripts/update-repos.sh"

  UploadToGHPages:
    steps:
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: .
